# Suba esse compose em seu ambiente. Siga as mesmas credenciais de acesso informada abaixo.
version: '3.7'

services:
  # ====================================================================================================================
  # POSTGRES SERVER
  # ====================================================================================================================
  postgres:
    image: postgres:15-alpine
    container_name: dev-postgresql
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: 1234567
    ports:
      - "5433:5432"
    volumes:
      - ./.data/postgresql/data:/var/lib/postgresql/data
    networks:
      - dev-network
  # ====================================================================================================================
  # PGADMIN
  # ====================================================================================================================
  pgadmin:
    image: dpage/pgadmin4
    container_name: dev-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: me@example.com
      PGADMIN_DEFAULT_PASSWORD: 1234567
    ports:
      - "5050:80"
    volumes:
      - ./.data/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres  # ✓ Corrigido para 'postgres'
    networks:
      - dev-network
  # ====================================================================================================================
  # REDE
  # ====================================================================================================================
networks:
  dev-network:  # ✓ Corrigido para 'dev-network'
    driver: bridge